### ISSUE TITLE
ManagedIdentity argument can be optimized

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.az#440]
Not all the argument for ManagedIdentity is needed. this should be a common case and can be optimized:
![image](https://user-images.githubusercontent.com/6038235/84978740-43c23800-b160-11ea-8cf7-2866eff80e78.png)

**Comment by qiaozha** [comment]
After confirmed with CLI guys, there's no such special logic to deal ManagedIdentity. We can't exclude there's some special scenarios where the principalId and tenantId can be updated. Given Network has similar definition for managedIdentities https://github.com/Azure/azure-rest-api-specs/blob/3c09c5f5e3a7c6a543ae1a9eea7f06a3cfda83a8/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/network.json#L193-L240 they set principalId and tenantId as readOnly, I would suggest we set the principalId and tenantId in ContainerRegistry as readOnly as well instead of trying to resolve it in codegen.

**Comment by RodgeFu** [comment]
Should the principal and tenant Id be readonly in most case? in that case, we should mark them as readonly by default and people can mark readonly=false when needed.

**Comment by qiaozha** [comment]
But the problem is that it's not straightforward to recognize whether a schema is managedidentities or not. As you can see in network it's called ManagedServiceIdentity and in containerregistry it's called IdentityProperties. we have to use some tricky way if we want to do that.

**Comment by RodgeFu** [comment]
hard for us to figure out whether the definition is for MSI. Suggest to update swagger or add directive to add readonly to handle this issue. thx
