### ISSUE TITLE
Should not label command group as experimental for CLI core

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#763]
Current codegen will label command group as experimental for CLI core, it's wrong behavior.
Below is the current generated code example:
```Python    
with self.command_group('vm', is_experimental=True):
        pass
```

**Comment by changlong-liu** [comment]
discuss detail in meeting

**Comment by qiaozha** [comment]
remove overall is_experimental=True,  for target-mode == 'core' instead of set it in each command group individually.

about default compatible-level value in target-mode == 'core'
1. don't change the default value for now. instead cli team will provide a list to set each services's default compatible level @jsntcy  
2. Code generator should output some info about which compatible-level is being used right now.

**Comment by qiaozha** [comment]
@jsntcy pending on cli team to provide the map befween cli modules and track1 and track1 mapping.

**Comment by changlong-liu** [comment]
Hi @jsntcy , please call us when the mapping is ready

**Comment by changlong-liu** [comment]
merged
